/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.DaoFoto;
import clases.Gerentedepaneles;
import ventanas.procesos.internal_facturacion;
import ventanas.archivos.internal_suplidores;
import ventanas.archivos.jinternal_preferencias;
import ventanas.archivos.internal_categoria;
import ventanas.archivos.internal_ayuda;
import ventanas.archivos.internal_clientes;
import ventanas.archivos.internal_productos;
import java.awt.Dimension;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.util.*;
import javax.swing.JDesktopPane;
import ventanas.archivos.jinternal_usuarios_ul;
import javax.swing.JOptionPane;
import ventanas.procesos.internal_entrada_inventario;
import ventanas.procesos.jinternal_Devoluciones;
import ventanas.procesos.jinternal_recivos;
import ventanas.procesos.jinternal_salida_inventario;


//http://gnuteam.blogspot.com/2011/08/abrir-solo-un-jinternalframe-por.html revisar
//https://www.youtube.com/watch?v=aKWXWtLacAY miralo para que solo se abra un internal frame 
// https://www.youtube.com/watch?v=SgDchpOoRrs 
/**
 *
 * @author Ing
 */
public class Menuses extends javax.swing.JFrame implements Runnable {
    Gerentedepaneles gerentedepaneles;
    private DaoFoto foto;
    private File archivo;
    private String hora, minutos, segundos, ampm;
    private Calendar calendario;
    private final Thread h1;
   
    //jinternal_preferencias   
    
    //constructor 
    public Menuses() {
        initComponents();
        this.setLocationRelativeTo(null);
        jm_fecha.setText(Fecha());
        h1 = new Thread(this);
        h1.start();
        User.setText("Francis Nathanael");
        lbl_name.setText("Francis");
        fonfo_pan.setVisible(false);
        this.gerentedepaneles = new Gerentedepaneles(fonfo_pan);
        
        
    }
    // Metodo que me genera la hora, minutos y segundos
    public void run() {
        Thread ct= Thread.currentThread();
        
        while(ct==h1){
            calcula();
            jm_reloj.setText(hora+":"+minutos+":"+segundos+" "+ampm);
            try{
                Thread.sleep(1000);
            }catch(InterruptedException e){}
        }
    }
    
    // Metodo que me calcula la fecha 
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        
        calendario.setTime(fechaHoraActual);
        ampm= calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }else{
            hora= calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY); 
        }
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
   
    // MEtodo que me genera la fecha
    public static String Fecha(){
         Date fecha=new Date();
         SimpleDateFormat FormatoFecha= new SimpleDateFormat("dd/MM/YYYY"); 
         return FormatoFecha.format(fecha);
    }

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        fonfo_pan = new javax.swing.JDesktopPane();
        foto_user = new javax.swing.JDesktopPane();
        userss = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Menu_principal = new javax.swing.JMenuBar();
        Jm_File = new javax.swing.JMenu();
        Jm_Preferencias = new javax.swing.JMenuItem();
        Jm_usuario = new javax.swing.JMenuItem();
        Jm_clientes = new javax.swing.JMenuItem();
        Jm_Productos = new javax.swing.JMenuItem();
        Jm_categoria = new javax.swing.JMenuItem();
        Jm_suplidor = new javax.swing.JMenuItem();
        Jm_Ayuda = new javax.swing.JMenuItem();
        Jm_salir = new javax.swing.JMenuItem();
        Jm_Procesos = new javax.swing.JMenu();
        Jm_facturacion = new javax.swing.JMenuItem();
        Jm_entra_inv = new javax.swing.JMenuItem();
        Jm_Salida_inventa = new javax.swing.JMenuItem();
        Jm_recivos = new javax.swing.JMenuItem();
        Jm_devoluciones = new javax.swing.JMenuItem();
        Jm_Reportes = new javax.swing.JMenu();
        Jm_productosR = new javax.swing.JMenuItem();
        Jm_facturasR = new javax.swing.JMenuItem();
        Jm_preciosR = new javax.swing.JMenuItem();
        Jm_recivosR = new javax.swing.JMenuItem();
        Jm_Ent_Sal_inv = new javax.swing.JMenuItem();
        Jm_devolucionesR = new javax.swing.JMenuItem();
        Jm_clientesR = new javax.swing.JMenuItem();
        Jm_balanceR = new javax.swing.JMenuItem();
        jm_reloj = new javax.swing.JMenu();
        jm_fecha = new javax.swing.JMenu();
        User = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fonfo_pan.setBackground(new java.awt.Color(255, 255, 255));
        fonfo_pan.setPreferredSize(new java.awt.Dimension(720, 720));

        javax.swing.GroupLayout fonfo_panLayout = new javax.swing.GroupLayout(fonfo_pan);
        fonfo_pan.setLayout(fonfo_panLayout);
        fonfo_panLayout.setHorizontalGroup(
            fonfo_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        fonfo_panLayout.setVerticalGroup(
            fonfo_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        escritorio.add(fonfo_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 974, 796));

        foto_user.setBackground(new java.awt.Color(255, 255, 255));
        foto_user.setForeground(new java.awt.Color(255, 255, 255));
        foto_user.setOpaque(false);

        userss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/userfinal.png"))); // NOI18N
        userss.setOpaque(true);

        foto_user.setLayer(userss, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout foto_userLayout = new javax.swing.GroupLayout(foto_user);
        foto_user.setLayout(foto_userLayout);
        foto_userLayout.setHorizontalGroup(
            foto_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        foto_userLayout.setVerticalGroup(
            foto_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userss, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        escritorio.add(foto_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        escritorio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, -1, -1));

        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("name");
        escritorio.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/este es.jpg"))); // NOI18N
        escritorio.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu_principal.setBackground(new java.awt.Color(255, 255, 255));
        Menu_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Jm_File.setBackground(new java.awt.Color(255, 255, 255));
        Jm_File.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivos.png"))); // NOI18N
        Jm_File.setMnemonic('A');
        Jm_File.setText("Archivos");
        Jm_File.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        Jm_Preferencias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_Preferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preferencias - Copy.png"))); // NOI18N
        Jm_Preferencias.setMnemonic('P');
        Jm_Preferencias.setText("Preferencias");
        Jm_Preferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_PreferenciasActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_Preferencias);

        Jm_usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        Jm_usuario.setMnemonic('U');
        Jm_usuario.setText("Usuarios");
        Jm_usuario.setToolTipText("");
        Jm_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_usuarioActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_usuario);

        Jm_clientes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        Jm_clientes.setMnemonic('C');
        Jm_clientes.setText("Clientes");
        Jm_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_clientesActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_clientes);

        Jm_Productos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        Jm_Productos.setMnemonic('M');
        Jm_Productos.setText("Productos");
        Jm_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_ProductosActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_Productos);

        Jm_categoria.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        Jm_categoria.setMnemonic('T');
        Jm_categoria.setText("Categorias");
        Jm_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_categoriaActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_categoria);

        Jm_suplidor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_suplidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/suplidores.png"))); // NOI18N
        Jm_suplidor.setMnemonic('S');
        Jm_suplidor.setText("Suplidores");
        Jm_suplidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_suplidorActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_suplidor);

        Jm_Ayuda.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Help_icon-icons.com_73700.png"))); // NOI18N
        Jm_Ayuda.setMnemonic('H');
        Jm_Ayuda.setText("Ayuda");
        Jm_Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_AyudaActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_Ayuda);

        Jm_salir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        Jm_salir.setMnemonic('L');
        Jm_salir.setText("Salir");
        Jm_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_salirActionPerformed(evt);
            }
        });
        Jm_File.add(Jm_salir);

        Menu_principal.add(Jm_File);

        Jm_Procesos.setBackground(new java.awt.Color(255, 255, 255));
        Jm_Procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procesos_1.png"))); // NOI18N
        Jm_Procesos.setText("Procesos");
        Jm_Procesos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        Jm_facturacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/e-invoicing como objeto inteligente-1.png"))); // NOI18N
        Jm_facturacion.setText("Facturacion");
        Jm_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_facturacionActionPerformed(evt);
            }
        });
        Jm_Procesos.add(Jm_facturacion);

        Jm_entra_inv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_entra_inv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventario3.png"))); // NOI18N
        Jm_entra_inv.setText("Entrada Inventario");
        Jm_entra_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_entra_invActionPerformed(evt);
            }
        });
        Jm_Procesos.add(Jm_entra_inv);

        Jm_Salida_inventa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_Salida_inventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iconos_Inventario-081.png"))); // NOI18N
        Jm_Salida_inventa.setText("Salida Inventario");
        Jm_Salida_inventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_Salida_inventaActionPerformed(evt);
            }
        });
        Jm_Procesos.add(Jm_Salida_inventa);

        Jm_recivos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_recivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recivo.png"))); // NOI18N
        Jm_recivos.setText("Recivos");
        Jm_recivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_recivosActionPerformed(evt);
            }
        });
        Jm_Procesos.add(Jm_recivos);

        Jm_devoluciones.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devoluciones.png"))); // NOI18N
        Jm_devoluciones.setText("Devoluciones");
        Jm_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jm_devolucionesActionPerformed(evt);
            }
        });
        Jm_Procesos.add(Jm_devoluciones);

        Menu_principal.add(Jm_Procesos);

        Jm_Reportes.setBackground(new java.awt.Color(255, 255, 255));
        Jm_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        Jm_Reportes.setText("Reportes");
        Jm_Reportes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        Jm_productosR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_productosR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventario_entrada.png"))); // NOI18N
        Jm_productosR.setText("Productos");
        Jm_Reportes.add(Jm_productosR);

        Jm_facturasR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_facturasR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportefactura.png"))); // NOI18N
        Jm_facturasR.setText("Facturas");
        Jm_Reportes.add(Jm_facturasR);

        Jm_preciosR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_preciosR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte devoluciones.png"))); // NOI18N
        Jm_preciosR.setText("Precios");
        Jm_Reportes.add(Jm_preciosR);

        Jm_recivosR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_recivosR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REPORTES_mybusinesspos.png"))); // NOI18N
        Jm_recivosR.setText("Recibos");
        Jm_Reportes.add(Jm_recivosR);

        Jm_Ent_Sal_inv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_Ent_Sal_inv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventory-management-300x3001.jpg"))); // NOI18N
        Jm_Ent_Sal_inv.setText("Entradas/Salidas Inventario");
        Jm_Reportes.add(Jm_Ent_Sal_inv);

        Jm_devolucionesR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_devolucionesR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportedevoluciones.png"))); // NOI18N
        Jm_devolucionesR.setText("Devoluciones");
        Jm_Reportes.add(Jm_devolucionesR);

        Jm_clientesR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_clientesR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        Jm_clientesR.setText("Clientes");
        Jm_Reportes.add(Jm_clientesR);

        Jm_balanceR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jm_balanceR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/balance.png"))); // NOI18N
        Jm_balanceR.setText("Balance");
        Jm_Reportes.add(Jm_balanceR);

        Menu_principal.add(Jm_Reportes);

        jm_reloj.setBackground(new java.awt.Color(255, 255, 255));
        jm_reloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reloj.png"))); // NOI18N
        jm_reloj.setText("Reloj");
        jm_reloj.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jm_reloj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Menu_principal.add(jm_reloj);

        jm_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jm_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        jm_fecha.setText("Fecha");
        jm_fecha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jm_fecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Menu_principal.add(jm_fecha);

        User.setText("User");
        User.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Menu_principal.add(User);

        setJMenuBar(Menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
       
    private void Jm_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_salirActionPerformed
        // TODO add your handling code here:
        Login jFrame= new Login();
        jFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jm_salirActionPerformed

    private void Jm_PreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_PreferenciasActionPerformed
        //controla_interno.abririnternal(jinternal_preferencias.getInstancia());
        gerentedepaneles.abririnternal(jinternal_preferencias.getInstancia());
        //mostrarpreferencias();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_PreferenciasActionPerformed

    private void Jm_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_usuarioActionPerformed
        // TODO add your handling code here:
        mostrarusuarios(); 
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_usuarioActionPerformed

    private void Jm_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_clientesActionPerformed
        // TODO add your handling code here:
        mostrarclientes();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_clientesActionPerformed

    private void Jm_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_ProductosActionPerformed
        // TODO add your handling code here:
       mostrarproductos();
       fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_ProductosActionPerformed

    private void Jm_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_categoriaActionPerformed
        // TODO add your handling code here:
       mostrarcategoria();
       fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_categoriaActionPerformed

    private void Jm_suplidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_suplidorActionPerformed
        // TODO add your handling code here:
        mostrarsuplidores();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_suplidorActionPerformed

    private void Jm_AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_AyudaActionPerformed
        // TODO add your handling code here:
       mostrarayuda();
       fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_AyudaActionPerformed

    private void Jm_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_facturacionActionPerformed
         mostrarfactura ();
         fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_facturacionActionPerformed

    private void Jm_entra_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_entra_invActionPerformed
        // TODO add your handling code here:
        mostrarentrada_inventario ();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_entra_invActionPerformed

    private void Jm_Salida_inventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_Salida_inventaActionPerformed
        mostrarsalida_inventario ();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_Salida_inventaActionPerformed

    private void Jm_recivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_recivosActionPerformed
        mostrar_recivo ();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_recivosActionPerformed

    private void Jm_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jm_devolucionesActionPerformed
        mostrar_Devoluciones ();
        fonfo_pan.setVisible(true);
    }//GEN-LAST:event_Jm_devolucionesActionPerformed
    
    // muestra un internal frame con las preferencias 
     private void mostrarpreferencias(){
         jinternal_preferencias v1 = new jinternal_preferencias();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();
         
    }
    private void mostrarusuarios(){
         jinternal_usuarios_ul v1 = new jinternal_usuarios_ul();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();                   
    }
    
    private void mostrarcategoria(){
         internal_categoria v1 = new internal_categoria();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();       
    }
    
    private void mostrarsuplidores(){
         internal_suplidores v1 = new internal_suplidores();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();       
    }
    
    private void mostrarayuda(){
         internal_ayuda v1 = new internal_ayuda();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();       
    }
    
    private void mostrarproductos(){
         internal_productos v1 = new internal_productos();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();       
    }
    
    private void mostrarclientes(){
         internal_clientes v1 = new internal_clientes();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();       
    }
    
    private void mostrarfactura (){
        internal_facturacion v1 = new internal_facturacion ();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();        
    }
    
    private void mostrarentrada_inventario (){
        internal_entrada_inventario v1 = new internal_entrada_inventario ();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();        
    }
    
    private void mostrarsalida_inventario (){
        jinternal_salida_inventario v1 = new jinternal_salida_inventario ();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();        
    }
    
    private void mostrar_recivo (){
        jinternal_recivos v1 = new jinternal_recivos ();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();        
    }
    
    private void mostrar_Devoluciones (){
        jinternal_Devoluciones v1 = new jinternal_Devoluciones ();
         fonfo_pan.add(v1);
         Dimension desktopSize = fonfo_pan.getSize();
         Dimension FrameSize = v1.getSize();
         v1.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
         v1.show();        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jm_Ayuda;
    private javax.swing.JMenuItem Jm_Ent_Sal_inv;
    private javax.swing.JMenu Jm_File;
    private javax.swing.JMenuItem Jm_Preferencias;
    private javax.swing.JMenu Jm_Procesos;
    private javax.swing.JMenuItem Jm_Productos;
    private javax.swing.JMenu Jm_Reportes;
    private javax.swing.JMenuItem Jm_Salida_inventa;
    private javax.swing.JMenuItem Jm_balanceR;
    private javax.swing.JMenuItem Jm_categoria;
    private javax.swing.JMenuItem Jm_clientes;
    private javax.swing.JMenuItem Jm_clientesR;
    private javax.swing.JMenuItem Jm_devoluciones;
    private javax.swing.JMenuItem Jm_devolucionesR;
    private javax.swing.JMenuItem Jm_entra_inv;
    private javax.swing.JMenuItem Jm_facturacion;
    private javax.swing.JMenuItem Jm_facturasR;
    private javax.swing.JMenuItem Jm_preciosR;
    private javax.swing.JMenuItem Jm_productosR;
    private javax.swing.JMenuItem Jm_recivos;
    private javax.swing.JMenuItem Jm_recivosR;
    private javax.swing.JMenuItem Jm_salir;
    private javax.swing.JMenuItem Jm_suplidor;
    private javax.swing.JMenuItem Jm_usuario;
    private javax.swing.JMenuBar Menu_principal;
    private javax.swing.JMenu User;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel fondo;
    private javax.swing.JDesktopPane fonfo_pan;
    private javax.swing.JDesktopPane foto_user;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jm_fecha;
    private javax.swing.JMenu jm_reloj;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel userss;
    // End of variables declaration//GEN-END:variables
}
